artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: C:\\mlops project\\archive.zip
  local_data_file : artifacts/data_ingestion/archive.zip
  unzip_dir : artifacts/data_ingestion


data_transformation:
  root_dir : artifacts/data_transformation
  data_path_black : artifacts/data_ingestion/ab/ab/ab1.npy
  data_path_grey : artifacts/data_ingestion/l/gray_scale.npy

model_building:
  root_dir : artifacts/model

model_trainer:
  root_dir : artifacts/trained_model
  test_data_path : artifacts/data_transformation/test_dataset.pt
  train_data_path : artifacts/data_transformation/train_dataset.pt

model_evaluation:
  test_data: 'artifacts/data_transformation/test_dataset.pt'
  generator_model: 'artifacts/trained_model/cwgan_generator_final.pt'
  critic_model: 'artifacts/trained_model/cwgan_critic_final.pt'
  


  
  